In [1]:
# allow matplotlib graphics to display in the notebook
%matplotlib inline
import matplotlib.pyplot

# import numpy, for image dimension manipulation
import numpy

# import validation methods from scikit-learn
from sklearn.metrics import precision_recall_fscore_support, accuracy_score

# import the dataset and neural network layers from keras
from keras.datasets import cifar10
from keras.models import Sequential, Model
from keras.layers.convolutional import Conv2D
from keras.layers import Dense, Flatten, Dropout, MaxPooling2D
from keras.optimizers import SGD
from keras.utils import to_categorical

Using TensorFlow backend.


In [2]:
# constants to describe the MNIST images
NUM_ROWS = 32
NUM_COLUMNS = 32
NUM_COLORS = 3
IMG_SHAPE = (NUM_ROWS, NUM_COLUMNS, NUM_COLORS)

# constant to describe the MNIST output labels
# there are ten different numbers, 0-9
NUM_CLASSES = 10

In [3]:
# load the data
((images_train, labels_train), (images_test, labels_test)) = cifar10.load_data()

170500096/170498071 [==============================] - 2s 0us/step


In [4]:
#I used the model on this site for designiing my model 
#https://adeshpande3.github.io/A-Beginner%27s-Guide-To-Understanding-Convolutional-Neural-Networks/
#Gus helped give ideas for parameters

model = Sequential()

# convolutional layers
model.add(Conv2D(input_shape=IMG_SHAPE,
                 filters=16*8, kernel_size=3, strides=1, padding='same', activation='tanh'))
model.add(Conv2D(filters=16*8, kernel_size=3, strides=1, padding='same', activation='tanh'))
model.add(Conv2D(filters=16*8, kernel_size=3, strides=1, padding='same', activation='relu'))
model.add(MaxPooling2D(pool_size=(2, 2)))
model.add(Dropout(0.25))
model.add(Conv2D(filters=32*8, kernel_size=3, strides=1, padding='same', activation='tanh'))
model.add(Conv2D(filters=32*8, kernel_size=3, strides=1, padding='same', activation='tanh'))
model.add(Conv2D(filters=32*8, kernel_size=3, strides=1, padding='same', activation='relu'))
model.add(MaxPooling2D(pool_size=(2, 2)))
model.add(Dropout(0.25))
model.add(Conv2D(filters=64*8, kernel_size=3, strides=1, padding='same', activation='tanh'))
model.add(Conv2D(filters=64*8, kernel_size=3, strides=1, padding='same', activation='tanh'))
model.add(Conv2D(filters=64*8, kernel_size=3, strides=1, padding='same', activation='relu'))
model.add(MaxPooling2D(pool_size=(2, 2)))
model.add(Dropout(0.25))
model.add(Flatten())
model.add(Dense(units=64*8, activation='relu'))
model.add(Dense(units=64*8, activation='relu'))


# output layer to make the final decision on which number it is
model.add(Dense(units=NUM_CLASSES, activation='softmax'))

In [5]:
model.summary()

Model: "sequential_1"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
conv2d_1 (Conv2D)            (None, 32, 32, 128)       3584      
_________________________________________________________________
conv2d_2 (Conv2D)            (None, 32, 32, 128)       147584    
_________________________________________________________________
conv2d_3 (Conv2D)            (None, 32, 32, 128)       147584    
_________________________________________________________________
max_pooling2d_1 (MaxPooling2 (None, 16, 16, 128)       0         
_________________________________________________________________
dropout_1 (Dropout)          (None, 16, 16, 128)       0         
_________________________________________________________________
conv2d_4 (Conv2D)            (None, 16, 16, 256)       295168    
_________________________________________________________________
conv2d_5 (Conv2D)            (None, 16, 16, 256)      

In [6]:
# the labels need to be one-hot encoded, to match the ten outputs of our model
labels_onehot_train = to_categorical(labels_train)

# set up the model to be ready for training
model.compile(optimizer=SGD(), loss='categorical_crossentropy', metrics=['accuracy'])

# fit the model to the training data
model.fit(images_train, labels_onehot_train, epochs=10)

Epoch 1/10
50000/50000 [==============================] - 38s 759us/step - loss: 1.8106 - accuracy: 0.3326
Epoch 2/10
50000/50000 [==============================] - 33s 668us/step - loss: 1.3395 - accuracy: 0.5167
Epoch 3/10
50000/50000 [==============================] - 33s 661us/step - loss: 1.0336 - accuracy: 0.6348
Epoch 4/10
50000/50000 [==============================] - 33s 665us/step - loss: 0.8574 - accuracy: 0.6981
Epoch 5/10
50000/50000 [==============================] - 33s 658us/step - loss: 0.7504 - accuracy: 0.7348
Epoch 6/10
50000/50000 [==============================] - 33s 666us/step - loss: 0.6591 - accuracy: 0.7702
Epoch 7/10
50000/50000 [==============================] - 33s 659us/step - loss: 0.5904 - accuracy: 0.7930
Epoch 8/10
50000/50000 [==============================] - 33s 664us/step - loss: 0.5281 - accuracy: 0.8142
Epoch 9/10
50000/50000 [==============================] - 33s 661us/step - loss: 0.4721 - accuracy: 0.8345
Epoch 10/10
50000/50000 [============

In [7]:
# get the predictions from the model
predictions_test_onehot = model.predict(images_test)

# get the index that has the highest probability
predictions_test = numpy.argmax(predictions_test_onehot, axis=1)

In [8]:
# get the overall accuracy
accuracy_score(y_true=labels_test, y_pred=predictions_test)

0.7764

In [9]:
# get precision, recall, f-score, and number of examples of each digit
# can you see which digits are easiest for the model, and which are hardest?
precision_recall_fscore_support(y_true=labels_test, y_pred=predictions_test)

(array([0.87133758, 0.88376561, 0.66221034, 0.69033048, 0.71010638,
        0.83851852, 0.70259939, 0.92196879, 0.7053637 , 0.90215054]),
 array([0.684, 0.92 , 0.743, 0.564, 0.801, 0.566, 0.919, 0.768, 0.96 ,
        0.839]),
 array([0.76638655, 0.90151886, 0.70028275, 0.62080352, 0.75281955,
        0.6758209 , 0.79636049, 0.83797054, 0.81321474, 0.86943005]),
 array([1000, 1000, 1000, 1000, 1000, 1000, 1000, 1000, 1000, 1000]))