In [1]:
# allow matplotlib graphics to display in the notebook
%matplotlib inline
import matplotlib.pyplot

# import numpy, for image dimension manipulation
import numpy

# import validation methods from scikit-learn
from sklearn.metrics import precision_recall_fscore_support, accuracy_score

# import the dataset and neural network layers from keras
from keras.datasets import mnist
from keras.models import Sequential, Model
from keras.layers.convolutional import Conv2D
from keras.layers import Dense, Flatten, Dropout, MaxPooling2D
from keras.optimizers import SGD
from keras.utils import to_categorical

Using TensorFlow backend.


In [2]:
# constants to describe the MNIST images
NUM_ROWS = 28 
NUM_COLUMNS = 28
NUM_COLORS = 1
IMG_SHAPE = (NUM_ROWS, NUM_COLUMNS, NUM_COLORS)

# constant to describe the MNIST output labels
# there are ten different numbers, 0-9
NUM_CLASSES = 10

In [3]:
# load the data
((images_train, labels_train), (images_test, labels_test)) = mnist.load_data()

11493376/11490434 [==============================] - 1s 0us/step


In [4]:
#I used the model on this site for designiing my model 
#https://adeshpande3.github.io/A-Beginner%27s-Guide-To-Understanding-Convolutional-Neural-Networks/
#Gus helped give ideas for parameters

model = Sequential()

# convolutional layers
model.add(Conv2D(input_shape=IMG_SHAPE,
                 filters=32, kernel_size=3, strides=1, padding='same', activation='relu'))
model.add(Conv2D(filters=32, kernel_size=3, strides=1, padding='same', activation='relu'))
model.add(MaxPooling2D(pool_size=(2, 2)))
model.add(Dropout(0.25))
model.add(Conv2D(filters=32, kernel_size=3, strides=1, padding='same', activation='relu'))
model.add(Conv2D(filters=32, kernel_size=3, strides=1, padding='same', activation='relu'))
model.add(Flatten())
model.add(Dense(units=8, activation='relu'))


# output layer to make the final decision on which number it is
model.add(Dense(units=NUM_CLASSES, activation='softmax'))

In [5]:
# keras requires a color dimension, so we need to expand each image to have one
images_3d_train = numpy.expand_dims(images_train, axis=3)

# the labels need to be one-hot encoded, to match the ten outputs of our model
labels_onehot_train = to_categorical(labels_train)

# set up the model to be ready for training
model.compile(optimizer=SGD(), loss='categorical_crossentropy', metrics=['accuracy'])

# fit the model to the training data
model.fit(images_3d_train, labels_onehot_train, epochs=15)

Epoch 1/15
60000/60000 [==============================] - 12s 193us/step - loss: 1.5615 - accuracy: 0.3748
Epoch 2/15
60000/60000 [==============================] - 8s 136us/step - loss: 0.4646 - accuracy: 0.8492
Epoch 3/15
60000/60000 [==============================] - 8s 139us/step - loss: 0.1492 - accuracy: 0.9596
Epoch 4/15
60000/60000 [==============================] - 9s 150us/step - loss: 0.1081 - accuracy: 0.9694
Epoch 5/15
60000/60000 [==============================] - 8s 138us/step - loss: 0.0894 - accuracy: 0.9751
Epoch 6/15
60000/60000 [==============================] - 8s 140us/step - loss: 0.0767 - accuracy: 0.9775
Epoch 7/15
60000/60000 [==============================] - 8s 135us/step - loss: 0.0640 - accuracy: 0.9815
Epoch 8/15
60000/60000 [==============================] - 8s 136us/step - loss: 0.0595 - accuracy: 0.9828
Epoch 9/15
60000/60000 [==============================] - 8s 137us/step - loss: 0.0536 - accuracy: 0.9837
Epoch 10/15
60000/60000 [====================

In [6]:
# keras requires a color dimension, so we need to expand each image to have one
images_3d_test = numpy.expand_dims(images_test, axis=3)

# get the predictions from the model
predictions_test_onehot = model.predict(images_3d_test)

# get the index that has the highest probability
predictions_test = numpy.argmax(predictions_test_onehot, axis=1)

In [7]:
# get the overall accuracy
accuracy_score(y_true=labels_test, y_pred=predictions_test)

0.9865

In [8]:
# get precision, recall, f-score, and number of examples of each digit
# can you see which digits are easiest for the model, and which are hardest?
precision_recall_fscore_support(y_true=labels_test, y_pred=predictions_test)

(array([0.99179487, 0.98085292, 0.99217986, 0.98328417, 0.98569969,
        0.98977273, 0.98440748, 0.98928919, 0.9825998 , 0.98615232]),
 array([0.98673469, 0.99295154, 0.98352713, 0.99009901, 0.98268839,
        0.9764574 , 0.98851775, 0.98832685, 0.98562628, 0.98810704]),
 array([0.98925831, 0.98686515, 0.98783455, 0.98667982, 0.98419174,
        0.98306998, 0.98645833, 0.98880779, 0.98411071, 0.98712871]),
 array([ 980, 1135, 1032, 1010,  982,  892,  958, 1028,  974, 1009]))